services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:z
    depends_on:
      - db

  db:
    image: mariadb:11.4.7 # Exact same version as production!
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mcu_app
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: Faiz14032002
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci # Force UTF-8 from the start!

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ciuser
      PMA_PASSWORD: supersecretpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
