services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:z
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mcu_app
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: Faiz14032002
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
